-- ==========================================
-- A股数据采集系统 - PostgreSQL Schema
-- ==========================================
-- 由 db/schema.sql 1:1 翻译 + 全部内联 DDL 表(admin_user / refresh_token /
-- app_settings / trading_calendar / scheduler_job / train_token)。
-- 首条语句为 datetime() 兼容函数(业务 SQL 里大量使用 datetime('now','localtime')
-- 与 datetime('now','-30 days'),必须最先注册,后续建表的 DEFAULT 才能引用)。
-- 转换规则:
--   REAL                      -> DOUBLE PRECISION
--   INTEGER PRIMARY KEY AUTOINCREMENT -> INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
--   TEXT/INTEGER 主键与复合主键保持原样
--   DEFAULT (datetime('now','localtime')) 原样保留
-- checkpoint_* 动态表不在此文件中(运行时创建,其 SQL 已兼容 PG)。

-- ==========================================
-- 0. datetime() 兼容函数(SQLite 语义)
-- ==========================================
-- 'localtime'            = 会话时区本地时间(now()::timestamp)
-- '[-+]N day(s)/hour(s)/minute(s)/second(s)' = now()::timestamp ± interval
-- 其他修饰符一律 RAISE EXCEPTION
CREATE OR REPLACE FUNCTION datetime(base text DEFAULT 'now', modifier text DEFAULT NULL)
RETURNS text AS $$
DECLARE
    mod_l text;
    v_ts  timestamp;
BEGIN
    IF lower(btrim(base)) <> 'now' THEN
        RAISE EXCEPTION 'datetime: unsupported base "%" (only ''now'' supported)', base;
    END IF;
    -- now()::timestamp 为会话时区本地时间,等价于 SQLite 'localtime' 语义
    v_ts := now()::timestamp;
    IF modifier IS NOT NULL THEN
        mod_l := lower(btrim(modifier));
        IF mod_l = 'localtime' THEN
            NULL;  -- v_ts 已是本地时间
        ELSIF mod_l ~ '^[-+]\s*\d+\s*(day|days|hour|hours|minute|minutes|second|seconds)$' THEN
            -- 去掉空白后直接转 interval,如 '-30 days' -> '-30days'
            v_ts := v_ts + regexp_replace(mod_l, '\s+', '', 'g')::interval;
        ELSE
            RAISE EXCEPTION 'datetime: unsupported modifier "%"', modifier;
        END IF;
    END IF;
    RETURN to_char(v_ts, 'YYYY-MM-DD HH24:MI:SS');
END;
$$ LANGUAGE plpgsql;

-- ==========================================
-- 1. 股票基础信息表
-- ==========================================
CREATE TABLE IF NOT EXISTS stock_list (
    code           TEXT PRIMARY KEY,         -- 股票代码(如 600000)
    name           TEXT,                     -- 股票名称
    full_code      TEXT,                     -- 带市场前缀(sh600000)
    industry       TEXT,                     -- 所属行业
    market         TEXT,                     -- 交易所(SH/SZ/BJ)
    list_date      TEXT,                     -- 上市日期
    is_active      INTEGER DEFAULT 1,        -- 是否在市
    updated_at     TEXT DEFAULT (datetime('now', 'localtime'))
);
CREATE INDEX IF NOT EXISTS idx_stock_list_market ON stock_list(market);
CREATE INDEX IF NOT EXISTS idx_stock_list_active ON stock_list(is_active);

-- 2. 日K线表(主键: code + trade_date + adjust_type)
CREATE TABLE IF NOT EXISTS kline_daily (
    code           TEXT NOT NULL,
    trade_date     TEXT NOT NULL,            -- YYYY-MM-DD
    open           DOUBLE PRECISION,
    high           DOUBLE PRECISION,
    low            DOUBLE PRECISION,
    close          DOUBLE PRECISION,
    pre_close      DOUBLE PRECISION,
    change_amount  DOUBLE PRECISION,        -- 涨跌额
    pct_change     DOUBLE PRECISION,        -- 涨跌幅(%)
    volume         BIGINT,                   -- 成交量(手, A股可达 60 亿+, 用 BIGINT)
    amount         DOUBLE PRECISION,        -- 成交额(元)
    turnover_rate  DOUBLE PRECISION,        -- 换手率(%)
    adjust_type    TEXT DEFAULT 'qfq',       -- qfq/hfq/none
    updated_at     TEXT DEFAULT (datetime('now', 'localtime')),
    PRIMARY KEY (code, trade_date, adjust_type)
);
CREATE INDEX IF NOT EXISTS idx_kline_daily_date ON kline_daily(trade_date);
CREATE INDEX IF NOT EXISTS idx_kline_daily_code ON kline_daily(code);

-- 3. 分钟K线表
CREATE TABLE IF NOT EXISTS kline_minute (
    code           TEXT NOT NULL,
    trade_time     TEXT NOT NULL,            -- YYYY-MM-DD HH:MM:SS
    period         INTEGER NOT NULL,         -- 1/5/15/30/60
    open           DOUBLE PRECISION,
    high           DOUBLE PRECISION,
    low            DOUBLE PRECISION,
    close          DOUBLE PRECISION,
    volume         BIGINT,
    amount         DOUBLE PRECISION,
    updated_at     TEXT DEFAULT (datetime('now', 'localtime')),
    PRIMARY KEY (code, trade_time, period)
);
CREATE INDEX IF NOT EXISTS idx_kline_minute_code ON kline_minute(code);
CREATE INDEX IF NOT EXISTS idx_kline_minute_time ON kline_minute(trade_time);

-- 4. 指数日线
CREATE TABLE IF NOT EXISTS index_daily (
    code           TEXT NOT NULL,            -- sh000001 等
    name           TEXT,
    trade_date     TEXT NOT NULL,
    open           DOUBLE PRECISION,
    high           DOUBLE PRECISION,
    low            DOUBLE PRECISION,
    close          DOUBLE PRECISION,
    volume         BIGINT,
    amount         DOUBLE PRECISION,
    pct_change     DOUBLE PRECISION,
    PRIMARY KEY (code, trade_date)
);

-- 5. 任务执行日志
CREATE TABLE IF NOT EXISTS update_log (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_name      TEXT NOT NULL,
    status         TEXT,                     -- success/failed/running
    affected_rows  INTEGER DEFAULT 0,
    start_time     TEXT,
    end_time       TEXT,
    message        TEXT
);
CREATE INDEX IF NOT EXISTS idx_log_task ON update_log(task_name);
CREATE INDEX IF NOT EXISTS idx_log_time ON update_log(start_time);

-- 6. 断点续传表(动态创建,见 checkpoint.py)

-- ==========================================
-- 训练交易系统表(独立于管理端,共用同一份股票数据)
-- ==========================================

-- 训练用户账户(独立账号体系,与管理后台 admin_user 分开)
CREATE TABLE IF NOT EXISTS training_user (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    salt          TEXT NOT NULL,
    display_name  TEXT,
    is_active     INTEGER DEFAULT 1,
    created_at    TEXT DEFAULT (datetime('now', 'localtime')),
    last_login    TEXT
);
CREATE INDEX IF NOT EXISTS idx_training_user_name ON training_user(username);

-- 用户钱包(训练资金,可消耗,用兑换码充值)
CREATE TABLE IF NOT EXISTS training_wallet (
    user_id        INTEGER PRIMARY KEY,
    balance        DOUBLE PRECISION DEFAULT 0,
    total_spent    DOUBLE PRECISION DEFAULT 0,
    total_topup    DOUBLE PRECISION DEFAULT 0,
    updated_at     TEXT DEFAULT (datetime('now', 'localtime'))
);

-- 兑换码(管理员下发或自注册,一次性使用,绑定金额)
CREATE TABLE IF NOT EXISTS redeem_code (
    code            TEXT PRIMARY KEY,
    amount          DOUBLE PRECISION NOT NULL,
    is_used         INTEGER DEFAULT 0,
    used_by         INTEGER,
    used_at         TEXT,
    created_by      TEXT,
    note            TEXT,
    revoked         INTEGER DEFAULT 0,           -- 1=管理员已作废(未使用的码)
    created_at      TEXT DEFAULT (datetime('now', 'localtime'))
);
CREATE INDEX IF NOT EXISTS idx_redeem_used ON redeem_code(is_used);
-- 老库兼容:revoked 列由 db/database.init_db 中的 ensure_col ALTER 添加

-- 训练会话(每次开始训练为 1 条;锁仓参数 + 时间范围 + 选定股票)
CREATE TABLE IF NOT EXISTS training_session (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         INTEGER NOT NULL,
    code            TEXT NOT NULL,                  -- 股票代码
    name            TEXT,                           -- 股票名称(快照)
    industry        TEXT,
    market          TEXT,
    start_date      TEXT NOT NULL,                  -- 用户选定的训练开始日(K线上 cutoff,只能看 < 此日 的数据)
    end_date        TEXT NOT NULL,                  -- 数据范围结束日(快照)
    lookback_months INTEGER DEFAULT 6,               -- 用于回看的历史数据月数
    initial_cash    DOUBLE PRECISION DEFAULT 1000000, -- 初始资金(快照)
    commission_rate DOUBLE PRECISION DEFAULT 0.0003, -- 手续费率
    min_commission  DOUBLE PRECISION DEFAULT 5,      -- 最低手续费
    stamp_tax       DOUBLE PRECISION DEFAULT 0.001,  -- 印花税(卖出)
    transfer_fee    DOUBLE PRECISION DEFAULT 0.00001,-- 过户费
    allow_split     INTEGER DEFAULT 1,               -- 是否允许分仓
    max_positions   INTEGER DEFAULT 5,               -- 最多持仓数量
    per_trade_amount DOUBLE PRECISION DEFAULT 100000,-- 每次下单金额
    allow_chinext   INTEGER DEFAULT 0,               -- 是否允许创业板
    allow_st        INTEGER DEFAULT 0,               -- 是否允许 ST 股
    allow_kcb       INTEGER DEFAULT 0,               -- 是否允许科创板
    allow_bj        INTEGER DEFAULT 0,               -- 是否允许北交所
    total_fee_paid  DOUBLE PRECISION DEFAULT 0,      -- 本次会话消耗的训练资金
    status          TEXT DEFAULT 'active',           -- active / finished
    reveal_date     TEXT,                            -- 已揭示到的日期 (粘性推进)
    auto_stop_loss_pct  DOUBLE PRECISION DEFAULT 0,  -- 2026-07-31 P2-3: 自动止损比例 (0=关闭, e.g. 0.08)
    auto_take_profit_pct DOUBLE PRECISION DEFAULT 0, -- 2026-07-31 P2-3: 自动止盈比例 (0=关闭)
    created_at      TEXT DEFAULT (datetime('now', 'localtime')),
    updated_at      TEXT DEFAULT (datetime('now', 'localtime'))
);
CREATE INDEX IF NOT EXISTS idx_session_user ON training_session(user_id);
CREATE INDEX IF NOT EXISTS idx_session_status ON training_session(status);

-- 训练订单(每次买入/卖出)
CREATE TABLE IF NOT EXISTS training_order (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id      INTEGER NOT NULL,
    user_id         INTEGER NOT NULL,
    trade_date      TEXT NOT NULL,                  -- 撮合交易日(=当时的 current_date)
    side            TEXT NOT NULL,                  -- BUY / SELL
    price           DOUBLE PRECISION NOT NULL,      -- 限价单的目标价 / 即时单的成交价
    quantity        INTEGER NOT NULL,
    amount          DOUBLE PRECISION NOT NULL,
    commission      DOUBLE PRECISION DEFAULT 0,
    stamp_tax       DOUBLE PRECISION DEFAULT 0,
    transfer_fee    DOUBLE PRECISION DEFAULT 0,
    total_fee       DOUBLE PRECISION DEFAULT 0,
    realized_pnl    DOUBLE PRECISION DEFAULT 0,     -- 卖出时累计盈亏
    pending_status  TEXT DEFAULT 'filled',          -- 2026-07-31 优化: filled / pending / cancelled / expired
    note            TEXT,
    created_at      TEXT DEFAULT (datetime('now', 'localtime'))
);
CREATE INDEX IF NOT EXISTS idx_order_session ON training_order(session_id);
CREATE INDEX IF NOT EXISTS idx_order_user_date ON training_order(user_id, trade_date);
CREATE INDEX IF NOT EXISTS idx_order_pending ON training_order(session_id, pending_status);

-- 训练当前持仓(每个 (session, code) 一行,数量+均价)
CREATE TABLE IF NOT EXISTS training_position (
    session_id      INTEGER NOT NULL,
    user_id         INTEGER NOT NULL,
    code            TEXT NOT NULL,
    quantity        INTEGER DEFAULT 0,
    avg_cost        DOUBLE PRECISION DEFAULT 0,
    updated_at      TEXT DEFAULT (datetime('now', 'localtime')),
    PRIMARY KEY (session_id, code)
);
CREATE INDEX IF NOT EXISTS idx_position_user ON training_position(user_id);
CREATE INDEX IF NOT EXISTS idx_position_user_code ON training_position(user_id, code);

-- 账户"权益曲线"快照,便于复盘 + 资金盈亏曲线
CREATE TABLE IF NOT EXISTS training_equity (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id      INTEGER NOT NULL,
    trade_date      TEXT NOT NULL,
    cash            DOUBLE PRECISION NOT NULL,
    market_value    DOUBLE PRECISION NOT NULL,
    total_equity    DOUBLE PRECISION NOT NULL,
    created_at      TEXT DEFAULT (datetime('now', 'localtime'))
);
CREATE INDEX IF NOT EXISTS idx_equity_session ON training_equity(session_id, trade_date);

-- 管理员操作日志(所有训练端 /api/train/admin/* 的写操作都进这张表,便于审计 / 追责)
CREATE TABLE IF NOT EXISTS admin_action_log (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor           TEXT NOT NULL,                   -- 操作者(用户名,目前固定为 admin)
    actor_kind      TEXT DEFAULT 'admin',            -- admin / system (留扩展)
    action          TEXT NOT NULL,                   -- 动作: create_redeem_codes / revoke_redeem_code / set_user_active /
                                                    -- reset_user_password / adjust_wallet / refund_used_code / delete_session ...
    target_type     TEXT,                            -- user / redeem_code / session
    target_id       TEXT,                            -- 目标主键的字符串形式(uid / 兑换码 / session_id)
    detail_json     TEXT,                            -- 详情(JSON 字符串,详情会因动作而异)
    reason          TEXT,                            -- 必填的调整原因
    before_value    TEXT,                            -- 动作前的关键值(如 balance)
    after_value     TEXT,                            -- 动作后的关键值
    ip              TEXT,                            -- 请求 IP(留扩展,可选)
    created_at      TEXT DEFAULT (datetime('now', 'localtime'))
);
CREATE INDEX IF NOT EXISTS idx_action_log_actor ON admin_action_log(actor, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_action_log_target ON admin_action_log(target_type, target_id);
CREATE INDEX IF NOT EXISTS idx_action_log_action ON admin_action_log(action);
CREATE INDEX IF NOT EXISTS idx_action_log_created ON admin_action_log(created_at DESC);

-- 训练 token 记录表(user.db)
-- 每个 token 落库一行,提供吊销能力。训练 token 这里是个简表(不像
-- admin_user 那样有 refresh_token 策略);老库迁移时无需从 stock.db
-- 搬运——线上 token 一次性失效,训练用户重新登录即可。
CREATE TABLE IF NOT EXISTS train_token (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     INTEGER NOT NULL,
    token       TEXT UNIQUE NOT NULL,
    refresh_jti TEXT,
    expires_at  TEXT NOT NULL,
    revoked     INTEGER DEFAULT 0,
    created_at  TEXT DEFAULT (datetime('now', 'localtime'))
);
CREATE INDEX IF NOT EXISTS idx_train_token_user ON train_token(user_id);
CREATE INDEX IF NOT EXISTS idx_train_token_token ON train_token(token);

-- 2026-07-31 P1-12: 训练事件流(支持撤销/回放)
-- 每个写动作记一条,含 payload 和 snapshot(撤销时回滚用)
CREATE TABLE IF NOT EXISTS training_event (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id    INTEGER NOT NULL,
    user_id       INTEGER NOT NULL,
    event_type    TEXT NOT NULL,            -- start / advance / buy / sell / finish / rollback
    trade_date    TEXT,                    -- 适用 buy/sell/advance
    payload_json  TEXT,                    -- 事件本身:订单 / 推进天数 / 起始资金
    snapshot_json TEXT,                    -- 事件前后快照:持仓 / 钱包 / reveal_date(用于回滚)
    note          TEXT,
    created_at    TEXT DEFAULT (datetime('now', 'localtime'))
);
CREATE INDEX IF NOT EXISTS idx_event_session  ON training_event(session_id, id DESC);
CREATE INDEX IF NOT EXISTS idx_event_user     ON training_event(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_event_type     ON training_event(event_type);

-- ==========================================
-- 内联 DDL 表(init_db / app.database / app.auth 中在线创建的表)
-- ==========================================

-- key-value 配置表(主源选择等持久化设置;原 db/database.py init_db 内联)
CREATE TABLE IF NOT EXISTS app_settings (
    key         TEXT PRIMARY KEY,
    value       TEXT NOT NULL,
    updated_at  TEXT DEFAULT (datetime('now', 'localtime'))
);

-- A 股交易日历(从指数 K线 推断;原 db/database.py init_db 内联)
CREATE TABLE IF NOT EXISTS trading_calendar (
    trade_date  TEXT PRIMARY KEY,
    updated_at  TEXT DEFAULT (datetime('now', 'localtime'))
);
CREATE INDEX IF NOT EXISTS idx_trading_calendar_date
    ON trading_calendar(trade_date);

-- 定时调度 job 配置表(每类数据一个 job;原 db/database.py init_db 内联)
CREATE TABLE IF NOT EXISTS scheduler_job (
    task         TEXT PRIMARY KEY,
    cron         TEXT NOT NULL,
    enabled      INTEGER NOT NULL DEFAULT 1,
    params_json  TEXT NOT NULL DEFAULT '{}',
    updated_at   TEXT DEFAULT (datetime('now', 'localtime')),
    last_run_at  TEXT,
    last_status  TEXT
);

-- 管理端用户表(原 app/database.py USER_SCHEMA)
CREATE TABLE IF NOT EXISTS admin_user (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username         TEXT UNIQUE NOT NULL,
    password_hash    TEXT NOT NULL,
    salt             TEXT NOT NULL,
    is_active        INTEGER DEFAULT 1,
    must_change_pw   INTEGER DEFAULT 0,     -- 1=下次登录必须改密
    created_at       TEXT DEFAULT (datetime('now', 'localtime')),
    last_login       TEXT,
    last_failed_login TEXT,
    failed_attempts  INTEGER DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_admin_username ON admin_user(username);

-- 管理端 refresh token(原 app/auth.py _ensure_refresh_table)
CREATE TABLE IF NOT EXISTS refresh_token (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     INTEGER NOT NULL,
    jti         TEXT UNIQUE NOT NULL,
    subject     TEXT NOT NULL,
    expires_at  TEXT NOT NULL,
    revoked     INTEGER DEFAULT 0,
    created_at  TEXT DEFAULT (datetime('now', 'localtime'))
);
